[project]
name = "authorityspoke"
version = "0.10.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "anchorpoint>=0.7.0",
    "eyecite~=2.6.3",
    "justopinion==0.4.0",
    "legislice==0.8.1",
    "lxml>=4.9.1",
    "nettlesome",
    "pint>=0.15",
    "pydantic",
    "python-dotenv",
    "python-ranges>=0.2.1",
    "python-slugify",
    "pyyaml",
    "requests",
    "roman",
    "sympy>=1.7.1",
]

[tool.uv.sources]
nettlesome = { git = "https://github.com/mscarey/nettlesome.git", rev = "absent-class" }

[dependency-groups]
dev = [
    "pytest-cov>=7.1.0",
    "pytest>=9.0.3",
    "pytest-recording>=0.13.4",
]

