[project]
name = "AuthoritySpoke"
version = "0.10.0"
description = "Reading legal authority for the last time"
readme = "README.rst"
requires-python = ">=3.14"
dependencies = [
    "pint>=0.25.3",
    "pydantic>=2.13.3",
    "python-slugify>=8.0.4",
    "sympy>=1.14.0",
    "anchorpoint>=0.7.0",
    "eyecite>=2.7.6",
    "justopinion",
    "legislice==0.8.2",
    "lxml>=4.9.1",
    "python-dotenv",
    "python-ranges>=0.2.1",
    "python-slugify",
    "pyyaml",
    "requests",
    "roman",
    "bidict>=0.23.1",
    "python-constraint2>=2.5.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest-cov>=7.1.0",
    "pytest>=9.0.3",
    "pytest-recording>=0.13.4",
    "sphinx>=9.1.0",
    "sphinx-autodoc-typehints>=3.10.2",
]
[tool.ruff.lint.per-file-ignores]
"decisions.py" = ["F401"]
"factors.py" = ["F401"]
"units.py" = ["F401"]

[tool.uv.sources]
justopinion = { git = "https://github.com/mscarey/justopinion.git", rev = "use-uv" }
legislice = { git = "https://github.com/mscarey/legislice.git", rev = "enactmentgroup-basemodel" }